// export const candidates = [
//     {   
//         id : 1, 
//         fname : "Jainish", 
//         lname : "Shah", 
//         is_hr_approved: false, 
//         is_manager_approved: false, 
//         is_hr_reject: false,
//         is_manager_reject:false,
//         age : 23, 
//         exp : 2,
        
//     },
//     {
//         id : 2, 
//         fname : "First", 
//         lname : "Last", 
//         is_hr_approved: false, 
//         is_manager_approved: false, 
//         is_hr_reject: false,
//         is_manager_reject:false,
//         age : 27, 
//         exp : 4,
        
//     },
//     {
//         id : 3,
//         fname : "Annapurna", 
//         lname : "Patil", 
//         is_hr_approved: false, 
//         is_manager_approved: false, 
//         is_hr_reject: false,
//         is_manager_reject:false,
//         age : 23, 
//         exp : 2,
        
//     },
//     {
//         id : 4,
//         fname : "Vivek", 
//         lname : "patil", 
//         is_hr_approved: false, 
//         is_manager_approved: false, 
//         is_hr_reject: false,
//         is_manager_reject:false,
//         age : 27, 
//         exp : 5,
        
//     },
//     {
//         id : 5,
//         fname : "Vivek", 
//         lname : "Patil 2", 
//         is_hr_approved: false, 
//         is_manager_approved: false, 
//         is_hr_reject: false,
//         is_manager_reject:false,
//         age : 27, 
//         exp : 5,
        
//     },
//     {
//         id : 6,
//         fname : "Annapurna", 
//         lname : "Patil 2", 
//         is_hr_approved: false, 
//         is_manager_approved: false, 
//         is_hr_reject: false,
//         is_manager_reject:false,
//         age : 27, 
//         exp : 5,
        
//     },
//     {
//         id : 7,
//         fname : "Jainish", 
//         lname : "Shah 2", 
//         is_hr_approved: false, 
//         is_manager_approved: false, 
//         is_hr_reject: false,
//         is_manager_reject:false,
//         age : 25, 
//         exp : 4,
        
//     },
//     {
//         id : 8,
//         fname : "Dummy", 
//         lname : "User", 
//         is_hr_approved: false, 
//         is_manager_approved: false, 
//         is_hr_reject: false,
//         is_manager_reject:false,
//         age : 40, 
//         exp : 15,
        
//     },
// ]